### ISSUE TITLE
Build fails against 3.18.10 kernel

### ISSUE THREAD

**Issue by bachmarc** [zfsonlinux/spl#441]
Hello,
I tried to build SPL/ZFS from gid repository against 3.18.10 after the first DKMS process failed.
I downloaded  0.6.3-3.tar.gz and tried => failed to build
I gave up and tried simple apt-get install debian-zfs => failed to build as well

At least here, I thought, nothing can go wrong.. it worked for 3.16 not for current kernel
```
# apt-get install debian-zfs
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  spl spl-dkms zfs-dkms
Vorgeschlagene Pakete:
  zfs-auto-snapshot
Die folgenden NEUEN Pakete werden installiert:
  debian-zfs spl spl-dkms zfs-dkms
0 aktualisiert, 4 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 0 B von 1.388 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 10,4 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] j
Vorkonfiguration der Pakete ...
Vormals nicht ausgewähltes Paket spl-dkms wird gewählt.
(Lese Datenbank ... 177638 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../spl-dkms_0.6.3-7~jessie_all.deb ...
Entpacken von spl-dkms (0.6.3-7~jessie) ...
spl-dkms (0.6.3-7~jessie) wird eingerichtet ...
Loading new spl-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.18.10
Building initial module for 3.18.10
Error! Bad return status for module build on kernel: 3.18.10 (x86_64)
Consult /var/lib/dkms/spl/0.6.3/build/make.log for more information.
Vormals nicht ausgewähltes Paket zfs-dkms wird gewählt.
(Lese Datenbank ... 177887 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../zfs-dkms_0.6.3-1~jessie_all.deb ...
Entpacken von zfs-dkms (0.6.3-1~jessie) ...
Vormals nicht ausgewähltes Paket spl wird gewählt.
Vorbereitung zum Entpacken von .../spl_0.6.3-7~jessie_amd64.deb ...
Entpacken von spl (0.6.3-7~jessie) ...
Vormals nicht ausgewähltes Paket debian-zfs wird gewählt.
Vorbereitung zum Entpacken von .../debian-zfs_7~jessie_amd64.deb ...
Entpacken von debian-zfs (7~jessie) ...
zfs-dkms (0.6.3-1~jessie) wird eingerichtet ...
Loading new zfs-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.18.10
Building initial module for 3.18.10
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.18.10 (x86_64)
Consult /var/lib/dkms/zfs/0.6.3/build/make.log for more information.
spl (0.6.3-7~jessie) wird eingerichtet ...
debian-zfs (7~jessie) wird eingerichtet ...
root@charon:/home/main/src# modprobe zfs
modprobe: FATAL: Module zfs not found.
```
I lost a bit overview from which try the make.log is a left-over... but it shows an issue.
```
# cat /var/lib/dkms/spl/builf/make.log

DKMS make.log for spl-0.6.3 for kernel 3.18.10 (x86_64)
Do 26. Mär 00:25:51 CET 2015
make  all-recursive
make[1]: Entering directory '/var/lib/dkms/spl/0.6.3/build'
Making all in module
make[2]: Entering directory '/var/lib/dkms/spl/0.6.3/build/module'
make -C /lib/modules/3.18.10/build SUBDIRS=`pwd`  O=/lib/modules/3.18.10/build CONFIG_SPL=m modules
make[3]: Entering directory '/usr/src/linux-headers-3.18.10'
make[4]: Entering directory '/usr/src/linux-headers-3.18.10'
  CC [M]  /var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-debug.o
  CC [M]  /var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.o
/var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.c: In function ‘spl_cache_grow’:
/var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.c:1921:7: warning: passing argument 3 of ‘wait_on_bit’ makes integer from pointer without a cast
       spl_cache_reclaim_wait, TASK_UNINTERRUPTIBLE);
       ^
In file included from /usr/src/linux-headers-3.18.10/include/linux/mmzone.h:9:0,
                 from /usr/src/linux-headers-3.18.10/include/linux/gfp.h:5,
                 from /usr/src/linux-headers-3.18.10/include/linux/kmod.h:22,
                 from /usr/src/linux-headers-3.18.10/include/linux/module.h:13,
                 from /var/lib/dkms/spl/0.6.3/build/include/sys/kmem.h:28,
                 from /var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.c:27:
/usr/src/linux-headers-3.18.10/include/linux/wait.h:887:1: note: expected ‘unsigned int’ but argument is of type ‘int (*)(void *)’
 wait_on_bit(void *word, int bit, unsigned mode)
 ^
/var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.c:1920:8: error: too many arguments to function ‘wait_on_bit’
   rc = wait_on_bit(&skc->skc_flags, KMC_BIT_REAPING,
        ^
In file included from /usr/src/linux-headers-3.18.10/include/linux/mmzone.h:9:0,
                 from /usr/src/linux-headers-3.18.10/include/linux/gfp.h:5,
                 from /usr/src/linux-headers-3.18.10/include/linux/kmod.h:22,
                 from /usr/src/linux-headers-3.18.10/include/linux/module.h:13,
                 from /var/lib/dkms/spl/0.6.3/build/include/sys/kmem.h:28,
                 from /var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.c:27:
/usr/src/linux-headers-3.18.10/include/linux/wait.h:887:1: note: declared here
 wait_on_bit(void *word, int bit, unsigned mode)
 ^
/var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.c: In function ‘spl_kmem_cache_reap_now’:
/var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.c:2364:2: error: implicit declaration of function ‘smp_mb__after_clear_bit’ [-Werror=implicit-function-declaration]
  smp_mb__after_clear_bit();
  ^
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.18.10/scripts/Makefile.build:257: recipe for target '/var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.o' failed
make[6]: *** [/var/lib/dkms/spl/0.6.3/build/module/spl/../../module/spl/spl-kmem.o] Error 1
/usr/src/linux-headers-3.18.10/scripts/Makefile.build:402: recipe for target '/var/lib/dkms/spl/0.6.3/build/module/spl' failed
make[5]: *** [/var/lib/dkms/spl/0.6.3/build/module/spl] Error 2
/usr/src/linux-headers-3.18.10/Makefile:1381: recipe for target '_module_/var/lib/dkms/spl/0.6.3/build/module' failed
make[4]: *** [_module_/var/lib/dkms/spl/0.6.3/build/module] Error 2
make[4]: Leaving directory '/usr/src/linux-headers-3.18.10'
Makefile:145: recipe for target 'sub-make' failed
make[3]: *** [sub-make] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-3.18.10'
Makefile:11: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/spl/0.6.3/build/module'
Makefile:578: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/spl/0.6.3/build'
Makefile:458: recipe for target 'all' failed
make: *** [all] Error 2

```
```
#cat /var/..../zfs/make.log
DKMS make.log for zfs-0.6.3 for kernel 3.18.10 (x86_64)
Do 26. Mär 00:36:11 CET 2015
make: *** Keine Targets angegeben und keine »make«-Steuerdatei gefunden.  Schluss.
=> German: No targets and no make config found
```

I only compiled 3.18.10 because of my kswapd0 issue with zfs unde 3.16... this is why my wife smiles and stays with windows ;o)
I was not able to find a debian 3.18.10 therefore I used a kernel.org xz to build it. I missed a secret patch??? 

Regards Marc

**Comment by kernelOfTruth** [comment]
I'm not really familiar with debian and it's kernel build process (not used all too often, I'm currently on Gentoo) - perhaps the following helps ?:

http://www.gargi.org/showthread.php?4560-Linux-Kernel-3-18-8-auf-Debian-kompilieren

I just wanted to object against 3.18 kernel but obviously the important patch against kswapd issues ( mm, vmscan: prevent kswapd livelock due to pfmemalloc-throttled process being killed ) is included since 3.18.3 ( http://www.gossamer-threads.com/lists/linux/kernel/2086129 )

**Comment by LzfyqzlVc9n4a1IZLyJ7NMqVdY3Br6PF** [comment]
For me it's because 0.6.3 is the latest release, there is no newer release.

**Comment by kernelOfTruth** [comment]
yes, you tried that

> I downloaded 0.6.3-3.tar.gz and tried => failed to build

hm,

related: https://github.com/zfsonlinux/spl/issues/434 , https://github.com/zfsonlinux/zfs/issues/2783 , https://github.com/zfsonlinux/zfs/issues/2810

https://github.com/zfsonlinux/spl/commit/e3020723dc43af2bc22af0d68571a61daf9b44d0

should fix it, which is included since 0.6.3-2



Did you encounter any issues with the KMOD approach ?

http://zfsonlinux.org/generic-deb.html

**Comment by bachmarc** [comment]
Ok, i gave it another try.... 

I removed everything from debian- zfs process... source.list, all packages related...reboot.

Debian approach is still not building  BUT the generic deb process starting from tar.gz builds now correctly... i have no idea why.

my system is running again! 


But still went not the way it should...all this should have been done by apt during installing new kernel. This triggered zfs module build is not reliable. Same as simple Debian  install builds only half.

Sooo closing ticket feels strange... but i cannot reproduce without risk or loss

**Comment by kernelOfTruth** [comment]
well, at least it worked :+1:

**Comment by behlendorf** [comment]
Closing.
